services:
    influxdb:
        image: influxdb:2
        container_name: gapp_influxdb
        restart: unless-stopped
        ports:
            - 8086:8086
        volumes:
            - ./.data/influxdb:/var/lib/influxdb2:rw

    mongodb:
        image: mongo:8
        container_name: gapp_mongodb
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./.data/mongodb:/data/db:rw
        environment:
            MONGO_INITDB_ROOT_USERNAME: fik
            MONGO_INITDB_ROOT_PASSWORD: tajne-heslo
            MONGO_INITDB_DATABASE: gapp
