services:
    influxdb:
        image: influxdb:2
        container_name: gapp_influxdb2
        restart: unless-stopped
        ports:
            - 8086:8086
        volumes:
            - ./.data/influxdb:/var/lib/influxdb2:rw
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=myusername
            - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpasswordpassword
            - DOCKER_INFLUXDB_INIT_ORG=myorg
            - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=some-long-secret-like-string

    mongodb:
        image: mongo:8
        container_name: gapp_mongodb
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./.data/mongodb:/data/db:rw
        environment:
            MONGO_INITDB_ROOT_USERNAME: fik
            MONGO_INITDB_ROOT_PASSWORD: tajne-heslo
            MONGO_INITDB_DATABASE: gapp

    gapp:
        image: ghcr.io/odz-ujf-av-cr/gapp:latest
        container_name: gapp
        depends_on:
            - influxdb
            - mongodb
        ports:
          - 3000:3000
        environment:
          - INFLUXDB_TOKEN=some-long-secret-like-string
          - INFLUXDB_HOST=http://influxdb:8086
          - MONGODB_URI=mongodb://fik:tajne-heslo@mongodb:27017
