services:
    influxdb:
        image: influxdb:2
        container_name: gapp_influxdb
        restart: unless-stopped
        ports:
            - 8086:8086
        volumes:
            - ./.data/influxdb:/var/lib/influxdb2:rw
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=user
            - DOCKER_INFLUXDB_INIT_PASSWORD=password
            - DOCKER_INFLUXDB_INIT_ORG=flight
            - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=development-influx-token

    postgres:
        image: postgres:17.4-alpine
        container_name: gapp_postgresdb
        restart: unless-stopped
        ports:
            - 5434:5432
        volumes:
            - ./.data/postgres:/var/lib/postgresql/data:rw
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=gapp

    mongodb:
        image: mongo:8
        container_name: gapp_mongodb
        restart: unless-stopped
        ports:
            - 27018:27017
        volumes:
            - ./.data/mongodb:/data/db:rw
        environment:
            MONGO_INITDB_ROOT_USERNAME: fik
            MONGO_INITDB_ROOT_PASSWORD: tajne-heslo
            MONGO_INITDB_DATABASE: gapp
