packages:
  - apps/**
  - packages/sondehub
  - packages/shared
  - packages/ui
  - packages/ui/libs/forms
  - packages/ui/libs/utils
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - less
  - lmdb
  - msgpackr-extract
onlyBuiltDependencies:
  - esbuild
